/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

(* top =  1  *)
(* src = "Mux_2x1.sv:1.1-9.10" *)
module Mux_2x1(i0, i1, sel, out);
  (* src = "Mux_2x1.sv:2.17-2.19" *)
  input i0;
  wire i0;
  (* src = "Mux_2x1.sv:3.17-3.19" *)
  input i1;
  wire i1;
  (* src = "Mux_2x1.sv:4.17-4.20" *)
  input sel;
  wire sel;
  (* src = "Mux_2x1.sv:5.18-5.21" *)
  output out;
  wire out;
  (* src = "Mux_2x1.sv:2.17-2.19" *)
  wire _0_;
  (* src = "Mux_2x1.sv:3.17-3.19" *)
  wire _1_;
  (* src = "Mux_2x1.sv:5.18-5.21" *)
  wire _2_;
  (* src = "Mux_2x1.sv:4.17-4.20" *)
  wire _3_;
  sky130_fd_sc_hd__mux2_1 _4_ (
    .A0(_0_),
    .A1(_1_),
    .S(_3_),
    .X(_2_)
  );
  assign _0_ = i0;
  assign _1_ = i1;
  assign _3_ = sel;
  assign out = _2_;
endmodule
